/**
 * Audit action vocabulary — ARCHITECTURE.md §18.5, §21.4.
 *
 * Stable action names for the append-only audit log. Foundation set; extended
 * as modules land (room, booking, user in later phases).
 */
export const AUDIT_ACTIONS = Object.freeze({
  // System
  SERVER_STARTED: 'SERVER_STARTED',
  // Auth (Phase 1B)
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOGOUT_ALL: 'USER_LOGOUT_ALL',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  TOKEN_REFRESHED: 'TOKEN_REFRESHED',
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET: 'PASSWORD_RESET',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',
  // Room (Phase 2)
  ROOM_CREATED: 'ROOM_CREATED',
  ROOM_UPDATED: 'ROOM_UPDATED',
  ROOM_DELETED: 'ROOM_DELETED',
  // Booking (Phase 3+)
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_APPROVED: 'BOOKING_APPROVED',
  BOOKING_REJECTED: 'BOOKING_REJECTED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  BOOKING_COMPLETED: 'BOOKING_COMPLETED',
  BOOKING_EXPIRED: 'BOOKING_EXPIRED',
});

export const AUDIT_ENTITY_TYPES = Object.freeze({
  USER: 'User',
  ROOM: 'Room',
  BOOKING: 'Booking',
  SYSTEM_CONFIG: 'SystemConfig',
});

export default AUDIT_ACTIONS;
