/**
 * Audit action vocabulary — ARCHITECTURE.md §18.5, §21.4.
 *
 * Stable action names for the append-only audit log. Foundation set; extended
 * as modules land (room, booking, user in later phases).
 */
export const AUDIT_ACTIONS = Object.freeze({
  // System
  SERVER_STARTED: 'SERVER_STARTED',
  // Auth (Phase 1B)
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOGOUT_ALL: 'USER_LOGOUT_ALL',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  TOKEN_REFRESHED: 'TOKEN_REFRESHED',
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET: 'PASSWORD_RESET',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',
  // User Management (Phase 1C)
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',
  USER_SELF_DELETED: 'USER_SELF_DELETED',
  USER_RESTORED: 'USER_RESTORED',
  USER_BLOCKED: 'USER_BLOCKED',
  USER_UNBLOCKED: 'USER_UNBLOCKED',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  USER_ROLE_APPROVED: 'USER_ROLE_APPROVED',
  USER_ROLE_REJECTED: 'USER_ROLE_REJECTED',
  USER_PROFILE_UPDATED: 'USER_PROFILE_UPDATED',
  USER_AVATAR_UPDATED: 'USER_AVATAR_UPDATED',
  USER_AVATAR_REMOVED: 'USER_AVATAR_REMOVED',

  // Room (Phase 2)
  ROOM_CREATED: 'ROOM_CREATED',
  ROOM_UPDATED: 'ROOM_UPDATED',
  ROOM_DELETED: 'ROOM_DELETED',
  ROOM_RESTORED: 'ROOM_RESTORED',
  ROOM_STATUS_CHANGED: 'ROOM_STATUS_CHANGED',
  ROOM_FACILITIES_UPDATED: 'ROOM_FACILITIES_UPDATED',
  ROOM_HOURS_UPDATED: 'ROOM_HOURS_UPDATED',
  ROOM_IMAGE_ADDED: 'ROOM_IMAGE_ADDED',
  ROOM_IMAGE_REMOVED: 'ROOM_IMAGE_REMOVED',
  ROOM_PRIMARY_IMAGE_SET: 'ROOM_PRIMARY_IMAGE_SET',
  // Booking (Phase 3+)
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_APPROVED: 'BOOKING_APPROVED',
  BOOKING_REJECTED: 'BOOKING_REJECTED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  BOOKING_COMPLETED: 'BOOKING_COMPLETED',
  BOOKING_EXPIRED: 'BOOKING_EXPIRED',
});

export const AUDIT_ENTITY_TYPES = Object.freeze({
  USER: 'User',
  ROOM: 'Room',
  BOOKING: 'Booking',
  SYSTEM_CONFIG: 'SystemConfig',
});

export default AUDIT_ACTIONS;
