/**
 * Booking model — ARCHITECTURE.md §18.3, §7.3 (indexes), §7.4 (time design).
 *
 * TIME IS STORED THREE WAYS (§7.4), by design:
 *   - bookingDate : Date normalised to 00:00 UTC  → first key of the conflict index
 *   - startTime/endTime : "HH:mm" strings         → display + form binding
 *   - startsAt/endsAt : full UTC Date             → AUTHORITATIVE for comparison
 * startsAt/endsAt/durationMinutes are DERIVED server-side in a pre-validate hook —
 * the client never supplies them, so they cannot be spoofed. This is data-layer
 * integrity, NOT business logic.
 *
 * EXPLICITLY NOT HERE (excluded from Phase 1A):
 *   - the conflict-detection query / findOverlapping static (§20) → service layer
 *   - min/max duration, capacity-vs-attendees, operating-hours checks (§19.3) → service
 *   - status transition rules / state machine (§21) → service
 * Only the compound INDEX that will support conflict detection is defined here.
 */
import mongoose from 'mongoose';

import {
  BOOKING_STATUS,
  BOOKING_STATUS_VALUES,
  RECURRENCE_TYPES,
  RECURRENCE_VALUES,
} from '../constants/bookingStatus.js';
import { toJSONPlugin } from './plugins/toJSON.plugin.js';

const { Schema, model } = mongoose;

const TIME_RE = /^([01]\d|2[0-3]):[0-5]\d$/;

const statusHistorySchema = new Schema(
  {
    status: { type: String, enum: BOOKING_STATUS_VALUES, required: true },
    changedBy: { type: Schema.Types.ObjectId, ref: 'User', default: null },
    changedAt: { type: Date, default: Date.now },
    reason: { type: String, trim: true, maxlength: 300 },
  },
  { _id: false }
);

const bookingSchema = new Schema(
  {
    // Human-quotable reference RF-YYYYMM-NNNN. Unique but generated by the
    // booking service (Phase 3); sparse so documents are valid before assignment.
    bookingRef: { type: String, unique: true, sparse: true, trim: true },

    room: { type: Schema.Types.ObjectId, ref: 'Room', required: [true, 'Room is required'] },
    user: { type: Schema.Types.ObjectId, ref: 'User', required: [true, 'User is required'] },

    // Denormalised for list/report rows (§9.3) — set by the service on create.
    roomCode: { type: String, trim: true },
    roomName: { type: String, trim: true },
    userName: { type: String, trim: true },

    bookingDate: { type: Date, required: [true, 'Booking date is required'] },
    startTime: { type: String, required: true, match: [TIME_RE, 'startTime must be HH:mm'] },
    endTime: { type: String, required: true, match: [TIME_RE, 'endTime must be HH:mm'] },

    // Derived (see pre-validate). Authoritative for sorting/overlap/reminders.
    startsAt: { type: Date },
    endsAt: { type: Date },
    durationMinutes: { type: Number, min: 1 },

    purpose: {
      type: String,
      required: [true, 'Purpose is required'],
      trim: true,
      minlength: [10, 'Purpose must be at least 10 characters'],
      maxlength: [500, 'Purpose cannot exceed 500 characters'],
    },
    attendees: { type: Number, required: true, min: [1, 'At least 1 attendee'] },

    status: {
      type: String,
      enum: { values: BOOKING_STATUS_VALUES, message: 'Invalid status: {VALUE}' },
      default: BOOKING_STATUS.PENDING,
    },

    // Approval / rejection / cancellation metadata (§18.3).
    approvedBy: { type: Schema.Types.ObjectId, ref: 'User', default: null },
    approvedAt: { type: Date, default: null },
    approvalRemark: { type: String, trim: true, maxlength: 300, default: null },
    rejectionReason: { type: String, trim: true, maxlength: 300, default: null },
    cancelledBy: { type: Schema.Types.ObjectId, ref: 'User', default: null },
    cancelledAt: { type: Date, default: null },
    cancellationReason: { type: String, trim: true, maxlength: 300, default: null },

    statusHistory: { type: [statusHistorySchema], default: [] },

    recurrence: {
      type: { type: String, enum: RECURRENCE_VALUES, default: RECURRENCE_TYPES.NONE },
      until: { type: Date, default: null },
      groupId: { type: Schema.Types.ObjectId, default: null, index: true },
    },

    reminderSent: { type: Boolean, default: false },
    attachments: {
      type: [{ url: String, publicId: String, name: String }],
      default: [],
    },
  },
  { timestamps: true }
);

bookingSchema.plugin(toJSONPlugin);

// --- Indexes (§7.3) ---
// THE conflict-detection index (ESR: Equality room+status, then date/time range).
bookingSchema.index({ room: 1, bookingDate: 1, status: 1, startTime: 1 });
bookingSchema.index({ user: 1, createdAt: -1 }); // "my bookings", newest first
bookingSchema.index({ status: 1, bookingDate: 1 }); // approval queue + daily reports
bookingSchema.index({ startsAt: 1 }); // reminder job scan

/**
 * Derive authoritative timestamps + normalise bookingDate to 00:00 UTC.
 * Data integrity only — no business rules. Runs when date/times are set.
 */
bookingSchema.pre('validate', function deriveTimes(next) {
  if (this.bookingDate && this.startTime && this.endTime) {
    const d = new Date(this.bookingDate);
    const y = d.getUTCFullYear();
    const m = d.getUTCMonth();
    const day = d.getUTCDate();

    // Normalise the day key to midnight UTC (first key of the conflict index).
    this.bookingDate = new Date(Date.UTC(y, m, day, 0, 0, 0, 0));

    const [sh, sm] = this.startTime.split(':').map(Number);
    const [eh, em] = this.endTime.split(':').map(Number);
    this.startsAt = new Date(Date.UTC(y, m, day, sh, sm, 0, 0));
    this.endsAt = new Date(Date.UTC(y, m, day, eh, em, 0, 0));

    if (this.endsAt <= this.startsAt) {
      this.invalidate('endTime', 'endTime must be after startTime');
    } else {
      this.durationMinutes = Math.round((this.endsAt - this.startsAt) / 60000);
    }
  }
  next();
});

export const Booking = model('Booking', bookingSchema);
export default Booking;
